"""Added column category to Quote table and daily_quote_category to User table

Revision ID: 4ce1807b2c34
Revises: b8f3eaa98c74
Create Date: 2025-07-11 13:05:36.718217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce1807b2c34'
down_revision = 'b8f3eaa98c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_quote_category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('daily_quote_category')

    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
