"""Added daily quote preferences to User table

Revision ID: b8f3eaa98c74
Revises: 3a7574301f11
Create Date: 2025-07-09 10:54:42.060577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f3eaa98c74'
down_revision = '3a7574301f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_quote_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('daily_quote_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('daily_quote_time')
        batch_op.drop_column('daily_quote_enabled')

    # ### end Alembic commands ###
